### ISSUE TITLE
Need help in running this

### ISSUE THREAD

**Issue by jayhohoho2019** [cmmarslender/xch-report#1]
Here is what I did:

Installed go 1.20.1 on ubuntu server 20.04.  
git clone  https://github.com/cmmarslender/xch-report
cd xch-report
go run main.go

**Comment by jayhohoho2019** [comment]
Never mind.  My bad in installing go.

**Comment by jayhohoho2019** [comment]
How could I run this to export transactions from another wallet key?

**Comment by cmmarslender** [comment]
> How could I run this to export transactions from another wallet key?

The way the RPC works is it just exports transactions from whatever key is "logged in" to the wallet currently.. So just run `chia wallet show` and select your other key, then run this app again

**Comment by jayhohoho2019** [comment]
Thank you.
